#Tasks:
Numpy Array Operations:
Scenario: You are given a list of daily average temperatures (in degrees Celsius) recorded over two
weeks. Your task is to use NumPy to analyze this data.

##1. Create a 1D NumPy Array:

Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [ ]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


#2. Inspection and Properties:

● Inspect the shape, data type, and the number of elements in the array. Inspect
the shape of the temperatures_w1 array.

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Shape:", temperatures_w1.shape)

print("Data type:", temperatures_w1.dtype)

print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7


#3. Array Operations:

● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:", temperatures_f)

max_temp = np.max(temperatures_w1)
print("Maximum Temperature:", max_temp)

min_temp = np.min(temperatures_w1)
print("Minimum Temperature:", min_temp)

mean_temp = np.mean(temperatures_w1)
print("Mean Temperature:", mean_temp)

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


#4. Array Slicing and Indexing:

● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

first_three_days = temperatures_w1[:3]
print("First three days:", first_three_days)

weekend = temperatures_w1[-2:]
print("Weekend:", weekend)

middle_three_days = temperatures_w1[2:5]
print("Middle three days:", middle_three_days)

First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


#5. Create a 2D Array:

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [ ]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


#6. Inspect and Slice the 2D Array:

● Inspect and print the shape, data type, and total number of elements in the
temperatures array.
● Extract the temperatures for each week and the weekends (last two days) for
both weeks.

In [ ]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("Shape of the array:", temperatures.shape)
print("Data type of elements:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

week1 = temperatures[0]
week2 = temperatures[1]

print("\nWeek 1 temperatures:", week1)
print("Week 2 temperatures:", week2)

weekend = temperatures[:, -2:]

print("\nWeekend temperatures (both weeks):")
print(weekend)

Shape of the array: (2, 7)
Data type of elements: float64
Total number of elements: 14

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend temperatures (both weeks):
[[24.8 21.9]
 [22.8 20.1]]


#Pandas Series:

##1. Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


#2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.
● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
labels.
● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
greater than 90.

In [ ]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

first_rank_mark = marks[0]

top3_marks = marks.loc[['Rank1', 'Rank2', 'Rank3']]


third_rank_mark = marks.iloc[2]

high_scores = marks[marks > 90]

print("1st Rank Mark:", first_rank_mark)
print("\nTop 3 Marks:\n", top3_marks)
print("\n3rd Rank Mark:", third_rank_mark)
print("\nMarks > 90:\n", high_scores)

1st Rank Mark: 95

Top 3 Marks:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank Mark: 89

Marks > 90:
 Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_1767/3353333429.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  first_rank_mark = marks[0]


#3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.
● Remove the entry corresponding to the last rank from the Series.
● Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

marks['Rank1'] = 100

print("\nAfter modifying Rank1:")
print(marks)

marks = marks.drop('Rank5')

print("\nAfter removing Rank5:")
print(marks)

cgpa = marks / 10

print("\nCGPA:")
print(cgpa)


After modifying Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


#Pandas DataFrame:

##1. Creating Pandas DataFrame:

● Create a Pandas DataFrame named transactions with the following data: ➢
TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',

'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [ ]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


#2. Data Exploration:
● Display the transactions DataFrame and its basic information, including head, tail,
shape, column names, and data types.
● Display only the 'ProductCategory' and 'Amount' columns.
● Retrieve the last 3 columns of the DataFrame using iloc or loc.
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
● Find the value counts for the 'ProductCategory' column.
● Find the unique values in the 'Region' column.
● Group by 'Region' and find the mean amount for each region.

In [ ]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print("\nTransactions")
print("\n",transactions)

print("\nHead")
print("\n",transactions.head())

print("\nTail")
print("\n",transactions.tail())

print("\nShape")
print("\n",transactions.shape)

print("\nColumn Names")
print("\n",transactions.columns)

print("\nData Types")
print("\n",transactions.dtypes)

print("\nProductCategory and Amount Columns")
print("\n",transactions[['ProductCategory', 'Amount']])

print("\nLast 3 columns of the DataFrame")
print("\n",transactions.iloc[:, -3:])

print("\nRegion is North and Amount is greater than 200")
filtered_data = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print("\n",filtered_data)

print("\nValue counts for the ProductCategory column")
print("\n",transactions['ProductCategory'].value_counts())

print("\nUnique values in the Region column")
print("\n",transactions['Region'].unique())

print("\nRegion Column and mean amount")
region_mean = transactions.groupby('Region')['Amount'].mean()
print("\n",region_mean)




Transactions

    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head

    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail

    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7       

#3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
● Add a new column 'Discount' by calculating 10% of the 'Amount'.
● Remove the row with TransactionID 109.
● Delete the 'Discount' column from the DataFrame.

In [ ]:
import pandas as pd

data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)

print("\nDataFrame")
print("\n",transactions)

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print("\nAfter Modifying Amount for TransactionID 102:\n")
print(transactions)

transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter Adding Discount Column:\n")
print(transactions)

transactions = transactions[transactions['TransactionID'] != 109]

print("\nAfter Removing TransactionID 109:\n")
print(transactions)

transactions = transactions.drop(columns=['Discount'])

print("\nFinal DataFrame after Deleting Discount Column:\n")
print(transactions)


DataFrame

    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After Modifying Amount for TransactionID 102:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clo